# Generated by Django 6.0.2 on 2026-03-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STARTED', 'Exam Started'), ('SUBMITTED', 'Exam Submitted'), ('AUTO_SUBMIT_TIME', 'Auto Submitted - Time Expired'), ('AUTO_SUBMIT_TAB', 'Auto Submitted - Tab Switch')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.submission')),
            ],
        ),
    ]
