# Generated by Django 6.0.2 on 2026-03-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
    ]
