# Generated by Django 6.0.2 on 2026-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
